apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-remote.yml
    kompose.version: 1.19.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: air-metadata-service-120
  name: air-metadata-service-120
spec:
  ports:
  - name: "20004"
    port: 20004
    targetPort: 9999
  - name: "30004"
    port: 30004
    targetPort: 7777
  selector:
    io.kompose.service: air-metadata-service-120
status:
  loadBalancer: {}
