apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-donors-dgraph-server-0
  labels:
    type: amazonEBS
    dataset: donors
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
---
