# There are 4 public services exposed, users can use:
#       dgraph-zero-public - To load data using Live & Bulk Loaders
#       dgraph-server-public - To connect clients and for HTTP APIs
#       dgraph-ratel-public - For Dgraph UI
#       dgraph-server-x-http-public - Use for debugging & profiling

apiVersion: v1
kind: Service
metadata:
  name: donors-dgraph-server-public
  labels:
    app: donors-dgraph-server
    dataset: donors
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: server-http
  - port: 9080
    targetPort: 9080
    name: server-grpc
  selector:
    app: donors-dgraph-server
---
# This service is created in-order to debug & profile a specific server.
# You can create one for each server that you need to profile.
# For a more general HTTP APIs use the above service instead.
apiVersion: v1
kind: Service
metadata:
  name: donors-dgraph-server-0-http-public
  labels:
    app: donors-dgraph-server
    dataset: donors
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: server-http
  selector:
    statefulset.kubernetes.io/pod-name: donors-dgraph-server-0
---
# This is a headless service which is neccessary for discovery for a dgraph-server StatefulSet.
# https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#creating-a-statefulset
apiVersion: v1
kind: Service
metadata:
  name: donors-dgraph-server
  labels:
    app: donors-dgraph-server
    dataset: donors
spec:
  ports:
  - port: 7080
    targetPort: 7080
    name: server-grpc-int
  clusterIP: None
  selector:
    app: donors-dgraph-server
---
# This StatefulSet runs 3 replicas of Dgraph Server.
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: donors-dgraph-server
spec:
  serviceName: "donors-dgraph-server"
  replicas: 1
  selector:
    matchLabels:
      app: donors-dgraph-server
  template:
    metadata:
      labels:
        app: donors-dgraph-server
        dataset: donors
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - donors-dgraph-server
              topologyKey: kubernetes.io/hostname
      containers:
      - name: server
        image: dgraph/dgraph:v1.0.7
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "9Gi"
          requests:
            memory: "8Gi"
        ports:
        - containerPort: 7080
          name: server-grpc-int
        - containerPort: 8080
          name: server-http
        - containerPort: 9080
          name: server-grpc
        volumeMounts:
        - name: datadir
          mountPath: /dgraph
        command:
          - bash
          - "-c"
          - |
            set -ex
            dgraph server --my=$(hostname -f):7080 --lru_mb 8192 --zero donors-dgraph-zero-0.donors-dgraph-zero.default.svc.cluster.local:5080
      terminationGracePeriodSeconds: 60
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 12Gi
