apiVersion: v1
kind: PersistentVolume
metadata:
  name: donors-dgraph-pv
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 12Gi
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-1/vol-02038f014c439fdd3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-donors-dgraph-server-0
  labels:
    type: amazonEBS
    dataset: donors
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: gp2
  volumeName: donors-dgraph-pv
---
